-- GameLog — add the 'awards' list kind
--
-- RUN THIS ON ITS OWN, BEFORE 0016.
--
-- The trap that split 0006/0007: Postgres refuses to let a new enum value be
-- *used* in the same transaction that adds it —
--
--   ERROR: unsafe use of new value "awards" of enum type list_kind
--   HINT:  New enum values must be committed before they can be used.
--
-- Strictly, 0016 could get away with one file: every reference to 'awards' in
-- it sits inside a plpgsql body, which is stored as text and not evaluated at
-- CREATE FUNCTION time — the same exemption that let 0005 add notification
-- kinds in place. It is split anyway, for two reasons. The exemption is a
-- detail of where the value happens to appear today, and the moment anyone adds
-- a CHECK, a DEFAULT or a partial index mentioning 'awards' the whole migration
-- starts failing for a reason that has nothing to do with their change. And
-- 0006 established the pattern, so a reader who has met that file already knows
-- what this one is for.

alter type public.list_kind add value if not exists 'awards';
