-- GameLog — add the 'captioned' list kind
--
-- RUN THIS ON ITS OWN.
--
-- Third time for this trap, and the file exists for the same reason 0006 and
-- 0015 do: Postgres refuses to let a new enum value be *used* in the same
-- transaction that adds it —
--
--   ERROR: unsafe use of new value "captioned" of enum type list_kind
--   HINT:  New enum values must be committed before they can be used.
--
-- Nothing else is needed. A captioned collection is an ordinary list whose
-- items each carry a line of the owner's own text, and `list_items.note` has
-- held exactly that since 0003 — `text check (char_length(note) <= 300)`, added
-- for a feature that never shipped and never removed. So the caption needs no
-- column, no table and no trigger: it needs a *kind*, so the client knows to
-- render the note as a heading under the cover rather than as a footnote, and
-- to ask for one when a game is added.
--
-- Reusing `note` rather than adding `caption` is deliberate. Two nullable text
-- columns on the same row, one of which is only ever populated for one list
-- kind, is the shape that produces a query somewhere reading the wrong one.

alter type public.list_kind add value if not exists 'captioned';
