-- GameLog — add the 'paused' log status
--
-- RUN THIS ON ITS OWN, before 0023.
--
-- Fourth time for this trap, and the file exists for the same reason 0006, 0015
-- and 0019 do: Postgres refuses to let a new enum value be *used* in the same
-- transaction that adds it —
--
--   ERROR: unsafe use of new value "paused" of enum type log_status
--   HINT:  New enum values must be committed before they can be used.
--
-- ## Why a status and not a completion level
--
-- The four statuses since 0001 answer "where does this game stand with me":
-- want to play it, playing it, played it, dropped it. "Paused" is an answer to
-- that same question — I have stopped, and I mean to come back — and it is not
-- the same answer as any of the four. It is not `playing` (I am not), not
-- `dropped` (that is the one that means *not* coming back), and not `played`
-- (which says the game is behind you).
--
-- How *far* you got is a different question, and 0023 answers it separately with
-- `logs.completion`. The two are independent on purpose: a game can be paused
-- after the credits rolled, while you finish its post-game.
--
-- An enum value rather than text + CHECK because `status` already is one, and
-- converting a column that four hundred queries filter on is not what this
-- change is for. The CHECK-over-enum rule (CLAUDE.md, gaming accounts) is for
-- new vocabularies; this one extends an existing type by one word.

alter type public.log_status add value if not exists 'paused';
